included: # paths to include during linting. `--path` is ignored if present.
  - WebNotificationsIOS
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
variable_name:
  min_length: 3
  excluded: # excluded via string array
    - x
    - y
    - m
    - n
    - id
    - URL
    - GlobalAPIKey
